### ISSUE TITLE
cephes update

### ISSUE THREAD

**Issue by simoneb** [AndreasMadsen/distributions#6]
Hey @AndreasMadsen, just a quick note to say that we've released a new major version of node-cephes, in case you're interested in upgrading. Hopefully there aren't any breaking changes, we did that just to bring that library back under control as we've been unable to build it for years now.

**Comment by AndreasMadsen** [comment]
Thanks for maintaining node-cephes. Sorry that the build broke, but I guess that is to be expected after 6 years. I have updated the deps for this package.

**Comment by simoneb** [comment]
Thanks for that, let us know if anything breaks
